### ISSUE TITLE
Emby crashes NAS when casting to chromecast

### ISSUE THREAD

**Issue by 2lach** [linuxserver/docker-emby#60]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

Ffmpeg transcoding process spikes CPU which results in the crash(es)
 ------------------------------

## Expected Behavior

I should be able to stream mp4 videos to my chromecast from emby with the app.

## Current Behavior

After the most recent emby update my NAS (open media vault) crashes whenever i use Emby. 
This occurs because of CPU overload. The reason behind this is ffmpeg transcodes the video. Last week i could stream mp4 videos from emby to chromecast via the emby app without any issues. 

## Steps to Reproduce

1. upgrade to emby Linuxserver.io version:- 4.7.8.0-ls132 Build-date:- 2022-10-09T04:58:05-05:00
2. cast with emby app to chromecast
3. enter htop, glances or similar process viewer 
4. watch how ffmpeg goes crazy....

## Environment
![sysinfo](https://user-images.githubusercontent.com/11457600/195149338-a03dbd5b-2247-494e-b114-f36ed4525ac4.jpg)

## Command used to create docker container (run/create/compose/screenshot)

```yaml

version: "2.1"
services:
  emby:
    image: lscr.io/linuxserver/emby:latest
    container_name: emby
    environment:
      - PUID=1000
      - PGID=1000
      - GIDLIST=44
      - TZ=Europe/Amsterdam
    volumes:
      - <path>/Config/Emby:/config
      - <path>/Tv:/tvshows
      - <path>/Movies:/movies
      - <path>/media:/media
    ports:
      - 8096:8096
    restart: on-failure:5 
```

## Docker logs

[docker logs emby.txt](https://github.com/linuxserver/docker-emby/files/9758355/docker.logs.emby.txt)

this shows how my system process spikes when starting emby
https://imgur.com/a/2NNFaaV

Don't dare to run it on chromecast again since then it was up to > 300%
cpu usage and honestly my server is not a fancy machine and i don't really know how many more crashes the cpu can take 😿 

Any advise on how to fix this would be much appreciated.

And while i'am here I just wanna say I have been using linuxserver docker images for years now, and this is the first time i ran into any issues (that i didn't cause myself) so just want send you all some ❤️  say thanks for all the AWESOME work you do! You guys truly rock!!!!
