### ISSUE TITLE
[BUG] Emby dashboard still reporting an update for v 4.7.12.0 after latest image release

### ISSUE THREAD

**Issue by vdrover** [linuxserver/docker-emby#69]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Yesterday Emby released an important security update, v4.7.12.

The latest release seems to suggest that linuxserver/docker-emby has been updated to 4.7.12.

 I shut down my docker stack, deleted the existing Emby image, pulled the latest image, and restarted the stack. However, my Emby dashboard still says it has the old version:

![Dashboard 2023-05-26 at 7 47 34 AM](https://github.com/linuxserver/docker-emby/assets/3143313/c9b66f58-a0dc-4233-8b84-7e6b15002ee3)

Docker is reporting the latest image:
![192 168 86 59 2023-05-26 at 7 53 16 AM](https://github.com/linuxserver/docker-emby/assets/3143313/00d95b04-2f6d-4d69-b328-42c3fac40e40)

### Expected Behavior

Emby should report version v4.7.12 when using the latest image.

### Steps To Reproduce

1. Stop Emby container. 
2. Delete Emby container.
3. Delete Emby image.
4. Pull latest Emby image. 
5. Restart container.

### Environment

```markdown
- OS: Ubuntu Jammy Jellyfish
- How docker service was installed: 

sudo apt update
sudo apt install apt-transport-https ca-certificates curl software-properties-common gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt update
sudo apt install docker-ce
sudo curl -L https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-`uname -s`-`uname -m` -o /usr/local/bin/docker-compose
sudo chmod +x /usr/local/bin/docker-compose
```
```


### CPU architecture

x86-64

### Docker creation

```bash
emby:
    container_name: emby
    image: lscr.io/linuxserver/emby:latest
    networks:
      - npm_proxy
    restart: always
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
    volumes:
      - $DOCKERDIR/appdata/emby:/config
      - $DATADIR/emby/tv:/data/tvshows
      - $DATADIR/emby/movies:/data/movies
      - $DATADIR/emby/home-videos:/data/home-videos
      - $DATADIR/emby/concerts:/data/concerts
      - $DATADIR/emby/sports:/data/sports
      - $DATADIR/emby/exercise:/data/exercise
      - $DATADIR/emby/dvr/shows:/data/dvr/shows
      - $DATADIR/emby/dvr/movies:/data/dvr/movies
      # - /dev/shm:/data/transcode
      # - /opt/vc/lib:/opt/vc/lib #optional
    ports:
      - "8096:8096"
      - "8920:8920" #optional
    devices:
      - /dev/fb0:/dev/dri #optional
```
```


### Container logs

```bash
05/26/2023 7:37:36 AM
[migrations] started
05/26/2023 7:37:36 AM
[migrations] no migrations found
05/26/2023 7:37:36 AM
───────────────────────────────────────
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
      ██╗     ███████╗██╗ ██████╗ 
05/26/2023 7:37:36 AM
      ██║     ██╔════╝██║██╔═══██╗
05/26/2023 7:37:36 AM
      ██║     ███████╗██║██║   ██║
05/26/2023 7:37:36 AM
      ██║     ╚════██║██║██║   ██║
05/26/2023 7:37:36 AM
      ███████╗███████║██║╚██████╔╝
05/26/2023 7:37:36 AM
      ╚══════╝╚══════╝╚═╝ ╚═════╝ 
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
   Brought to you by linuxserver.io
05/26/2023 7:37:36 AM
───────────────────────────────────────
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
To support LSIO projects visit:
05/26/2023 7:37:36 AM
https://www.linuxserver.io/donate/
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
───────────────────────────────────────
05/26/2023 7:37:36 AM
GID/UID
05/26/2023 7:37:36 AM
───────────────────────────────────────
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
User UID:    1000
05/26/2023 7:37:36 AM
User GID:    1000
05/26/2023 7:37:36 AM
───────────────────────────────────────
05/26/2023 7:37:36 AM
05/26/2023 7:37:36 AM
**** adding /dev/dri to video group video with id 44 ****
05/26/2023 7:37:36 AM
[custom-init] No custom files found, skipping...
05/26/2023 7:37:36 AM
Info Main: Application path: /app/emby/EmbyServer.dll
05/26/2023 7:37:36 AM
Info Main: Emby
05/26/2023 7:37:36 AM
	Command line: /app/emby/EmbyServer.dll -programdata /config -ffdetect /app/emby/ffdetect -ffmpeg /app/emby/ffmpeg -ffprobe /app/emby/ffprobe -restartexitcode 3
05/26/2023 7:37:36 AM
	Operating system: Linux version 5.19.0-41-generic (buildd@lcy02-amd64-045) (x86_64-linux-gnu-gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, GNU ld (GNU Binutils for Ubunt
05/26/2023 7:37:36 AM
	Framework: .NET 6.0.8
05/26/2023 7:37:36 AM
	OS/Process: x64/x64
05/26/2023 7:37:36 AM
	Runtime: app/emby/System.Private.CoreLib.dll
05/26/2023 7:37:36 AM
	Processor count: 12
05/26/2023 7:37:36 AM
	Data path: /config
05/26/2023 7:37:36 AM
	Application path: /app/emby
05/26/2023 7:37:36 AM
Info Main: Logs path: /config/logs
05/26/2023 7:37:36 AM
Info Main: Cache path: /config/cache
05/26/2023 7:37:36 AM
Info Main: Internal metadata path: /config/metadata
05/26/2023 7:37:36 AM
Info Main: Transcoding temporary files path: /config/transcoding-temp
05/26/2023 7:37:36 AM
Info App: Application version: 4.7.11.0
```
```
